---
driver:
  name: vagrant
  box: chef-centos-6.6
  box_url:  https://atlas.hashicorp.com/jcalonsoh/boxes/chef-centos-6.6/versions/1.0.0/providers/virtualbox.box
  customize:
    memory: 2048
    cpus: 4
    nictype2: 'Am79C970A'
  synced_folders:
    - ["./chef", "/chef"]

provisioner:
  name: chef_solo
  chef_omnibus_url: file:///chef/installer/install.sh

platforms:
  - name: chef-centos-6.6
    driver:
      network:
        - ['public_network', bridge: 'em1']

suites:
  - name: web1
    run_list:
      - recipe[agentJ_nginx::default]
    attributes:
    driver_config:
      hostname: web1
      network:
        - ["forwarded_port", {guest: 80, host: 8081}]
  - name: web2
    run_list:
      - recipe[agentJ_nginx::default]
    attributes:
    driver_config:
      hostname: web2
      network:
        - ["forwarded_port", {guest: 80, host: 8082}]